### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by MockerTim**
Added integration test for the OneWay/Pull MEP.

### CODE REVIEW

**Comment by MockerTim** [comment]
Hi Sander,
Please, let me know if there is something to fix in this pull request.

**Comment by sfieten** [comment]
Hi Timur,
I just tried to do a clean build of the code and that should an interesting dependency issue. In the build process the distribution zip packaging is of course one of the last steps as the other modules need to be compiled before they can be included in the zip. 
The integration test now included in the Core module however depend on the zip being available. Since this is not the case in a clean build the process stops. To be able to run the integration tests I needed first to trigger the build process without tests, so the zip was created.

However the issue is more generic I think as the integration tests will run before a new zip file is created. I therefore think the integration tests should be moved to the distribution module. Which makes sense as they are a kind of test of the distribution zip.

Can you a look how to refactor the integration tests so this issue is resolved? If you're refactoring anyway, could you also have a look at the names of these classes, which are not that clear to me. I noticed this is the default naming convention of the Maven failsafe plugin, but also found this [article](https://www.javacodegeeks.com/2015/01/separating-integration-tests-from-unit-tests-using-maven-failsafe-junit-category.html) showing how to create your own naming.

**Comment by MockerTim** [comment]
Hi Sander,
I'm going to fix this issue ASAP.

Best Regards,
Timur Shakuov

2017-02-02 23:00 GMT+03:00 Sander Fieten <notifications@github.com>:

**Comment by MockerTim** [comment]
I've added changes to the separate pull request.

**Comment by sfieten** [comment]
Hi Timur, 
since you opened a new pull request, I guess we can close this one?

**Comment by MockerTim** [comment]
Hi Sander,
Sure. We can close this one.

**Pull request closed without merging**
