### PR TITLE
Added MessageProccesingEventHandlingException which is thrown at IMessageProcessingEventHandlerFactory::init

### PR DESCRIPTION
**Pull request by jerouris**

### CODE REVIEW

**Comment by sfieten** [comment]
Hi @jerouris, 
with this new exception, should the `IMessageProcessingEventHandler.handleEvent` method also use it? It now uses the general `IllegalArgumentException`, but if we add a specific exception it's maybe better to use it here as well?

**Comment by sfieten** [comment]
Oh, and could you be so kind to edit the Javadoc of the new exception so it relates to the event processing instead of message delivery ;-)

**Comment by jerouris** [comment]
Yes, I make the changes and make a new pull request

**Comment by jerouris** [comment]
fixed

**Comment by sfieten** [comment]
Thanks @jerouris for these updates!

**Pull request merged**
